version: '3'

services:
  medmolnet-front:
    image: medmolnet-frontend
    build:
      context: ./frontend  # Corrected to use context
      dockerfile: Dockerfile  # Corrected to use dockerfile key
    volumes:
      - ./frontend/src:/usr/src/app/src  # Sync local frontend code
    networks:
      - medmolnet-network

  medmolnet-back:
    image: medmolnet-backend
    build:
      context: ./backend  # Corrected to use context
      dockerfile: Dockerfile  # Corrected to use dockerfile key
    volumes:
      - ./backend:/python-docker  # Sync local backend code
    networks:
      - medmolnet-network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    networks:
      - medmolnet-network

# Uncomment and configure certbot if needed
# certbot:
#   image: certbot/certbot
#   container_name: certbot
#   depends_on:
#     - nginx
#   volumes: 
#     - ./certbot/conf:/etc/letsencrypt
#     - ./certbot/www:/var/www/certbot
#   command: certonly --webroot -w /var/www/certbot  --email nitzanmr@gmail.com -d proteinnetworksight.jce.ac -d medmolnet.jce.ac --expand --agree-tos --non-interactive
#   networks:
#     - medmolnet-network

networks:
  medmolnet-network:
    driver: bridge
